load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
load("@bazel_tools//tools/build_defs/repo:git.bzl", "new_git_repository")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

local_repository(
    name = "hello",
    path = "../localBazelProj",
)

new_local_repository(
    name = "openssl",
    path = "../localProj",
    build_file = "BUILD.openssl",
)

git_repository(
    name = "googletest",
    remote = "https://github.com/google/googletest",
    branch = "v1.10.x",
)

new_git_repository(
    name = "bazelTest",
    remote = "https://github.com/zhangjianxiongZJX/test.git",
    commit = "f675ab36437eec682d72996ee376fa2758e5d32b",
    build_file = "BUILD.test",
)

http_archive(
    name = "rules_proto",
    sha256 = "602e7161d9195e50246177e7c55b2f39950a9cf7366f74ed5f22fd45750cd208",
    strip_prefix = "rules_proto-97d8af4dc474595af3900dd85cb3a29ad28cc313",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_proto/archive/97d8af4dc474595af3900dd85cb3a29ad28cc313.tar.gz",
        "https://github.com/bazelbuild/rules_proto/archive/97d8af4dc474595af3900dd85cb3a29ad28cc313.tar.gz",
    ],
)


load("@rules_proto//proto:repositories.bzl", "rules_proto_dependencies", "rules_proto_toolchains")
rules_proto_dependencies()
rules_proto_toolchains()
